### ISSUE TITLE
接收到的消息中文乱码

### ISSUE THREAD

**Issue by leezoes** [103style/mqtt_demo#1]
```dart
   final String data =
          MqttPublishPayload.bytesToStringAsString(recMess.payload.message)
```
您好 , 接收到的消息中文乱码, 该怎么处理

**Comment by 103style** [comment]
你可以在  [mqtt_client 这个库 ](https://github.com/shamblett/mqtt_client)  这里问下作者

**Comment by leezoes** [comment]
收发消息时都转换成UTF-8就可以了，谢谢。
> https://github.com/shamblett/mqtt_client/issues/46

**Comment by 103style** [comment]
@leezoes  :tada:
